### ISSUE TITLE
Linked Example Dashboard is not working

### ISSUE THREAD

**Issue by splosch** [telerik/vue-dashboard#5]
The linked example at [https://telerik.github.io/vue-dashboard/#/](https://telerik.github.io/vue-dashboard/#/) fails to load data via

`https://api.github.com/repos/telerik/kendo-ui-core/issues?state=all&page=1&per_page=100`

Results in 
```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

Reason for posting this Issue on an rather stale Project is the active Link on [https://www.telerik.com/kendo-vue-ui/components/](https://www.telerik.com/kendo-vue-ui/components/) where its highlighted as a Sample Vue-Application

**Comment by zdravkov** [comment]
So sorry about this inconvenience caused.  It is working now. 

As a side note - the code is a bit out dated but all of the components in it are already available as [native Kendo vue components ](https://www.telerik.com/kendo-vue-ui/components/) and soon we will create an updated version with vue3 that will show the scenario without jQuery.
Greetings,
Plamen
